#title: "GAIL: Guaranteed Automatic Integration Library "
#description: "GAIL is a suite of algorithms for integration problems in one, many dimensions, and whose answers are guaranteed to be correct. "
#google_analytics: true
#show_downloads: true
#theme: jekyll-theme-cayman

#gems:
#  - jekyll-mentions
name: "YOURNAME"                                # CHANGE HERE 
output_dir: "."
navbar:
  title: "YOURNAME"                             # CHANGE HERE 
  type: inverse
  left:
    - text: "Home"
      icon: fa-home
      href: index.html
    - text: "About"
      icon: fa-user 
      href: about.html
    - text: "CV"
      icon: fa-file-pdf-o
      href: cv.html
    - text: "Blog"
      icon: fa-rss
      href: https://YOURGITHUB.github.io/blog/  # CHANGE HERE OR DELETE ALL 3 LINES 
  right:
    - text: "Contact me"
      icon: fa-envelope-o
      href: mailto:YOUREMAIL                    # CHANGE HERE 
    - text: "GitHub"
      icon: fa-github
      href: https://github.com/YOURGITHUB       # CHANGE HERE output:
  html_document:
    theme: cosmo
    highlight: textmate